SUPABASE_URL="https://psyadarbmtnmcvbgaeja.supabase.co"
SUPABASE_PUBLISHABLE_KEY="sb_publishable_jqQxAoioX62zCiuMyb0c5w_HUS7Oek6"
SUPABASE_SECRET_KEY="sb_secret_wK3wcBTL6BPbuUU0zatXOg_uhYMFeAb"
SUPABASE_JWKS_URL="https://psyadarbmtnmcvbgaeja.supabase.co/auth/v1/.well-known/jwks.json"